/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package cesafi_registration;

import com.github.sarxos.webcam.Webcam;
import com.github.sarxos.webcam.WebcamPanel;
import com.github.sarxos.webcam.WebcamResolution;
import java.awt.BorderLayout;
import java.awt.Color;
import java.awt.Cursor;
import java.awt.Dimension;
import java.awt.event.MouseEvent;
import java.awt.event.MouseListener;
import java.io.File;
import java.util.ArrayList;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;
import javax.swing.JFrame;
import javax.swing.JLabel;
import javax.swing.JPanel;
import javax.swing.Timer;
import javax.swing.border.EmptyBorder;

/**
 *
 * @author Rosalijos
 */
public class Camera extends javax.swing.JPanel{

    /**
     * Creates new form Camera
     * 
     * 
     */
    
    private Dimension ds;
    private Dimension cs;
       
    private Webcam wCam;
    private WebcamPanel wCamPanel;    
    private JLabel countdown = new JLabel();
    private JFrame frame;
    private Thread v;
    private JPanel pnl_CameraHolder;
    
    public Camera() {
        initComponents();
    }

    public void startVideo(JPanel pnl_CameraHolder){
        Thread t = new Thread(){
            @Override
            public void run(){
                    ((WebcamPanel)pnl_CameraHolder).start();
            }
        };
        
        t.setDaemon(true);
        t.start();        
    }
    
    
    public JPanel initializeVideo(int index){
        ds = new Dimension(554, 384);
        cs = WebcamResolution.VGA.getSize();
        wCam = Webcam.getWebcams().get(index);
        wCamPanel = new WebcamPanel(wCam, ds, false);
        //wCamPanel.setLayout(new BorderLayout());
        wCam.setViewSize(cs);
        wCamPanel.setFillArea(true);
        return wCamPanel;
    }
    
    public ImageIcon takeImage(String filePath){    
        ImageIcon img = null;
        try{
            ImageIO.write(wCam.getImage(), "JPG", new File(filePath));
            img = new ImageIcon(filePath);
        }catch(Exception e){
        }
        return img;
    }
    
    public ImageIcon takeImage(String filePath, int width, int height){    
        ImageIcon img = null;
        try{
            ImageIO.write(wCam.getImage(), "JPG", new File(filePath));
            img = Images.changeSize(new ImageIcon(filePath), width, height);
        }catch(Exception e){
        }
        return img;
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnl_Camera = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        pnl_Camera1 = new javax.swing.JPanel();

        setLayout(new java.awt.BorderLayout());

        pnl_Camera.setBackground(new java.awt.Color(240, 240, 20));
        pnl_Camera.setLayout(new java.awt.BorderLayout());
        add(pnl_Camera, java.awt.BorderLayout.CENTER);

        jPanel4.setLayout(new java.awt.BorderLayout());

        pnl_Camera1.setBackground(new java.awt.Color(240, 240, 20));
        pnl_Camera1.setLayout(new java.awt.BorderLayout());
        jPanel4.add(pnl_Camera1, java.awt.BorderLayout.CENTER);

        add(jPanel4, java.awt.BorderLayout.PAGE_START);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel pnl_Camera;
    private javax.swing.JPanel pnl_Camera1;
    // End of variables declaration//GEN-END:variables
}
